[query]
kind = "files"
include = [
  "*.pt",
  "*.pth",
  "*.onnx",
  "*.safetensors",
  "*.ckpt",
  "*.h5",
  "*pytorch_model.bin"
]
exclude = []

[evaluator]
kind = "builtin"
name = "paths_none_match"

[evaluator.options]

[judge]
kind = "bool_true"
